version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "message_rabbitmq3.8"
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
