version: '3.9'

services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: "xxl-job"
    environment:
      - PARAMS="--spring.config.location=/application.properties"
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/data/applogs
      - /home/eiheihei/g/s2077.github/compose/prod/xxl-job/config/application.properties:/application.properties 
    networks:
      - lab