version: '3.3'

services:
  dnsmasq:
    # https://hub.docker.com/r/jpillora/dnsmasq
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/udp"
      - 8006:8080
    volumes:
      - type: bind
        source: ./config/dnsmasq.conf
        target: /etc/config.yml
      - type: bind
        source: ./config/resolv.conf
        target: /etc/resolv.conf
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"