# include RabbitMQ, 
version: "3.9"

volumes:
  rabbitmq-data1:
    name: rabbitmq-data1
  rabbitmq-conf1:
    name: rabbitmq-conf1   

networks:
  rabbitmq:
    driver: bridge
    ipam:
      config:
      - subnet: "10.10.10.0/16"      

services:
  rabbitmq01:
    image: rabbitmq:3.8-management
    container_name: rabbitmq01
    profiles:
      - rabbitmq
    hostname: rabbitmq01
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data1:/var/lib/rabbitmq
      - rabbitmq-conf1:/etc/rabbitmq
    networks:
      rabbitmq:
        ipv4_address: "10.10.10.0"        
