# include RabbitMQ, 
version: "3.9"

volumes:
  rabbitmq-data:
    name: rabbitmq-data
  rabbitmq-conf:
    name: rabbitmq-conf    

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    profiles:
      - rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=wallet
      - RABBITMQ_DEFAULT_PASS=wallet
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-conf:/etc/rabbitmq
    networks:
      - lab     