version: '3.3'

services:
  traefik:
    image: traefik:v2.8.7
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    # command: --api.insecure=true --providers.docker
    networks:
      - lab
    # https://suyang.wiki/runbook/traefik/issue-certs.html
    # environment:
    #   - CF_API_EMAIL=${CF_API_EMAIL}
    #   - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    #   - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}

    volumes:
      # 仅限标准的 Linux 环境
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./config/:/etc/traefik/config/:ro
      # - ./ssl/:/data/ssl/
      - type: bind
        source: ./config/traefik.toml
        target: /etc/traefik/traefik.toml   
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      retries: 12
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.lab.local`)"
      - "traefik.http.routers.api.service=api@internal"

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      # 设置Host 为 whoami.docker.localhost 进行域名访问
      - "traefik.http.routers.whoami.rule=Host(`whoami.lab.local`)" 
    networks:
      - lab