version: '3.3'

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ${SYNC_CONFIG_PATH}:/config
      - ${SYNC_DATA_PATH}:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    networks:
      - lab
    restart: unless-stopped
