version: '3.3'

volumes:
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data
  grafana-datasource:
    name: grafana-datasource
  grafana-dashboard:
    name: grafana-dashboard

# reference: https://soulteary.com/2021/10/30/private-cloud-environment-installed-in-a-notebook-monitor.html
services:
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    profiles:
      - prometheus
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=1y"
      # 根据自己需求来考虑是否开启
      # https://prometheus.io/docs/prometheus/latest/migration/#prometheus-lifecycle
      - "--web.enable-lifecycle"
    expose:
      - 9090
    ports:
      - 9090:9090
    networks: 
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    profiles:
      - prometheus
      - nodeexporter  
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"     
    restart: always
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  
  cadvisor:
    # gcr images mirror: https://github.com/anjia0532/gcr.io_mirror
    image: anjia0532/cadvisor.cadvisor:v0.45.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    profiles:
      - prometheus
      - cadvisor 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      # 仅限 Linux 环境使用
      - /cgroup:/cgroup:ro
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  
  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
    profiles:
      - prometheus
      - pushgateway       
    expose:
      - 9091
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"      

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - type: bind
        source: ${ALERTMANAGER_CONFIG_PATH}
        target: /etc/alertmanager/config.yml
    profiles:
      - prometheus
      - alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: always
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  
  grafana:
    image: grafana/grafana:9.0.9
    container_name: grafana
    user: "root"
    profiles:
      - prometheus
      - grafana
    volumes:
      - grafana-data:/data:z
      # 根据自己情况，是否需要持久化面板配置 :)
      - grafana-dashboard:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_PATHS_DATA=${GF_PATHS_DATA}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - lab
    logging:
      driver: "json-file"
      options:
        max-size: "1m"